from __future__ import annotations

from .mappers import map_checklist_step, map_portal_session, map_portal_session_item, normalize_step_category
from .models import (
    ChecklistSessionItemRecord,
    ChecklistSessionRecord,
    ChecklistStep,
    ChecklistTemplateItemRecord,
    CustomerPortalSession,
    CustomerPortalSessionItem,
    JobStatus,
    StepCategory,
)
from .repo import (
    CHECKLIST_SESSION_FIELDS,
    CHECKLIST_SESSION_ITEM_FIELDS,
    CHECKLIST_TEMPLATE_ITEM_FIELDS,
    complete_session,
    create_session,
    get_active_session,
    get_session,
    get_session_items,
    get_template_items,
    list_sessions,
    update_session_item,
)
from .service import (
    complete_session as complete_session_service,
    ensure_active_session,
    require_session,
    require_session_item,
    update_session_item as update_session_item_service,
    upload_session_item_proof,
)

__all__ = [
    "CHECKLIST_SESSION_FIELDS",
    "CHECKLIST_SESSION_ITEM_FIELDS",
    "CHECKLIST_TEMPLATE_ITEM_FIELDS",
    "ChecklistSessionItemRecord",
    "ChecklistSessionRecord",
    "ChecklistStep",
    "ChecklistTemplateItemRecord",
    "CustomerPortalSession",
    "CustomerPortalSessionItem",
    "JobStatus",
    "StepCategory",
    "complete_session",
    "complete_session_service",
    "create_session",
    "ensure_active_session",
    "get_active_session",
    "get_session",
    "get_session_items",
    "get_template_items",
    "list_sessions",
    "map_checklist_step",
    "map_portal_session",
    "map_portal_session_item",
    "normalize_step_category",
    "require_session",
    "require_session_item",
    "update_session_item",
    "update_session_item_service",
    "upload_session_item_proof",
]
