from __future__ import annotations

import frappe


_PERMISSION_FIELDS = (
	"select",
	"read",
	"write",
	"create",
	"delete",
	"submit",
	"cancel",
	"amend",
	"mask",
	"report",
	"export",
	"import",
	"share",
	"print",
	"email",
	"if_owner",
	"impersonate",
)

_BUILDING_CUSTOM_DOCPERMS = (
	{
		"role": "Accounts Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 0,
		"create": 0,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 0,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Accounts User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 0,
		"create": 0,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 0,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Digital Walkthrough Reviewer",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 0,
		"create": 0,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 0,
		"export": 1,
		"import": 0,
		"share": 0,
		"print": 0,
		"email": 0,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "HR Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "HR User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Maintenance Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 1,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Maintenance User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Sales Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 1,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Sales User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "System Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 1,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
)

_BUILDING_SOP_CUSTOM_DOCPERMS = (
	{
		"role": "Accounts Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 0,
		"create": 0,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 0,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Accounts User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 0,
		"create": 0,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 0,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "HR Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "HR User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Maintenance Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Maintenance User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Sales Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "Sales User",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
	{
		"role": "System Manager",
		"permlevel": 0,
		"select": 1,
		"read": 1,
		"write": 1,
		"create": 1,
		"delete": 0,
		"submit": 0,
		"cancel": 0,
		"amend": 0,
		"mask": 0,
		"report": 1,
		"export": 1,
		"import": 0,
		"share": 1,
		"print": 1,
		"email": 1,
		"if_owner": 0,
		"impersonate": 0,
	},
)


def _permission_fields() -> tuple[str, ...]:
	meta = frappe.get_meta("Custom DocPerm")
	return tuple(field for field in _PERMISSION_FIELDS if meta.get_field(field))


def _permission_values(row: dict, permission_fields: tuple[str, ...]) -> dict:
	return {field: int(row.get(field) or 0) for field in permission_fields}


def _permission_key(row: dict) -> tuple[str, int]:
	return (row["role"], int(row.get("permlevel") or 0))


def _ensure_custom_docperms(doctype_name: str, desired_rows: tuple[dict, ...]) -> None:
	if not frappe.db.exists("DocType", doctype_name):
		return

	permission_fields = _permission_fields()
	desired_by_key = {_permission_key(row): row for row in desired_rows}
	existing_rows = frappe.get_all(
		"Custom DocPerm",
		filters={"parent": doctype_name},
		fields=["name", "role", "permlevel", *permission_fields],
		order_by="creation asc",
	)

	existing_by_key = {}
	rows_to_delete = []
	for row in existing_rows:
		key = _permission_key(row)
		if key not in desired_by_key or key in existing_by_key:
			rows_to_delete.append(row["name"])
			continue
		existing_by_key[key] = row

	for row_name in rows_to_delete:
		frappe.delete_doc("Custom DocPerm", row_name, force=1, ignore_permissions=True)

	for key, desired in desired_by_key.items():
		values = {
			"parent": doctype_name,
			"role": desired["role"],
			"permlevel": desired["permlevel"],
			**_permission_values(desired, permission_fields),
		}
		existing = existing_by_key.get(key)
		if not existing:
			frappe.get_doc({"doctype": "Custom DocPerm", **values}).insert(ignore_permissions=True)
			continue

		current_permissions = _permission_values(existing, permission_fields)
		if current_permissions == _permission_values(desired, permission_fields):
			continue

		doc = frappe.get_doc("Custom DocPerm", existing["name"])
		doc.update(values)
		doc.save(ignore_permissions=True)

	frappe.clear_cache(doctype=doctype_name)


def ensure_building_custom_docperms() -> None:
	_ensure_custom_docperms("Building", _BUILDING_CUSTOM_DOCPERMS)


def ensure_building_sop_custom_docperms() -> None:
	_ensure_custom_docperms("Building SOP", _BUILDING_SOP_CUSTOM_DOCPERMS)
